import Head from "next/head";
import styles from "../styles/layout.module.scss";

function Layout({ children }) {
  return (
    <div lang="en">
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <main className={styles.container}>
          <div className={styles.content}>{children}</div>
        </main>
      </div>
    </div>
  );
}

export default Layout;
